# Generated by Django 4.2.6 on 2023-10-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetosg10app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
    ]
