# Generated by Django 4.2.6 on 2023-10-15 22:14

from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('email', models.EmailField()),
                ('tipologin', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Padrinho'), (3, 'Voluntário')], default=1)),
            ],
        ),
    ]