# Generated by Django 4.2.6 on 2023-10-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardimdogotasapp', '0002_rename_usuario_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
